version: '{build}'
image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu
configuration:
  - Release
  - Debug
platform:
  - x64

init:
  - cmd: set generator="%APPVEYOR_BUILD_WORKER_IMAGE% Win64"
  - cmd: echo %generator%

install:
  - git submodule update --init --recursive

before_build:
  - sh: echo Running before_build on ubuntu
  - sh: pwd
  - cmd: echo Running before_build on windows
  - mkdir build
  - cd build
  - cmake --version
  - sh: cmake ..
  - cmd: cmake -G %generator% ..

build:
  project: build\ChristmasLightShowMaker.sln
  verbosity: minimal
  parallel: true
